# Generated by Django 2.1.2 on 2018-10-25 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.CharField(max_length=30, verbose_name='Client')),
                ('streetaddress', models.CharField(max_length=300, verbose_name='Street Address')),
                ('city', models.CharField(max_length=30, verbose_name='City')),
                ('state', models.CharField(max_length=30, verbose_name='State')),
                ('date', models.DateField(verbose_name='Date Performed')),
                ('zip', models.CharField(max_length=5, verbose_name='Zip Code')),
                ('date_end', models.DateField(blank=True, default=None, null=True, verbose_name='Date Ended')),
                ('contact', models.CharField(max_length=100, verbose_name='Contact')),
                ('email', models.EmailField(default=None, max_length=254, null=True, verbose_name='Email')),
                ('subnets', models.CharField(default=None, max_length=300, null=True, verbose_name='Subnets')),
            ],
        ),
        migrations.CreateModel(
            name='Network_object',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Firewall/Router/Switch Name')),
                ('make', models.CharField(max_length=30, verbose_name='Brand')),
                ('model', models.CharField(max_length=30, verbose_name='Model')),
                ('description', models.CharField(blank=True, default=None, max_length=1000, null=True, verbose_name='Description')),
                ('client', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='para.Client', verbose_name='Client')),
            ],
        ),
    ]
