version: '2'
services:
  nginx:
    image: nginx:latest
    container_name: ncart-ng01
    ports:
      - "80:80"
    volumes:
      - ./:/src
      - ./config/nginx:/etc/nginx/conf.d
    depends_on:
      - web
  web:
    build: .
    container_name: web
    command: bash -c "python3 manage.py makemigrations && python3 manage.py migrate && gunicorn paraweb.wsgi  -b 0.0.0.0:8000"
    depends_on:
      - db
    volumes:
      - ./:/src
    expose:
      - "8000"

  db:
    image: postgres:latest
    container_name: db